/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.tesco.eos.Main;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class MainTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
